/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;
/**
 *
 * @author Acer
 */
public class LOGIN extends javax.swing.JFrame {

    private int counterFromFacade;

    public LOGIN(int counter) {
        initComponents();
        this.counterFromFacade = counter;
        
        // Call the method for USERID field
        clearTextFieldOnClick(USERID);

        // Call the method for PASSWORD field
        clearTextFieldOnClick(PASSWORD);
    }
 
    private void clearTextFieldOnClick(javax.swing.JTextField textField) {
        textField.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (!textField.getText().isEmpty()) {
                    textField.setText("");
                    textField.removeMouseListener(this); // Remove the listener after clearing
                }
            }
        });
    }
    
    private void openFacultyFrame(String userID, String lastName, String firstname, String course) {
        java.awt.EventQueue.invokeLater(() -> {
            new StudentGradingSystem(userID, lastName, firstname, course).setVisible(true); // Open Faculty frame
        });
    }

    private void openStudentFrame() {
        java.awt.EventQueue.invokeLater(() -> {
            new STUDENT().setVisible(true); // Open Student frame
        });
    }

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }
    
    // Create a method to clear the user input fields
    private void clearUserInput() {
        USERID.setText(""); // Clearing the text field for userID
        PASSWORD.setText(""); // Clearing the password field
    }
    
    private void openStudentFrame(String userID, String lastName, String firstName) {
        java.awt.EventQueue.invokeLater(() -> {
            new STUDENT(userID, lastName, firstName).setVisible(true); // Pass user info to the STUDENT frame
        });
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        USERID = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        SHOW = new javax.swing.JCheckBox();
        LOGIN = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentGradingSystem");
        setBackground(new java.awt.Color(255, 204, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(380, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_project/icons8-plasmid-100.png"))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STUDENT GRADING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        USERID.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        USERID.setText("USER ID");
        USERID.setBorder(null);
        USERID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERIDActionPerformed(evt);
            }
        });

        PASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PASSWORD.setText("PASSWORD");
        PASSWORD.setBorder(null);
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });

        SHOW.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        SHOW.setText("Show Password");
        SHOW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        SHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWActionPerformed(evt);
            }
        });

        LOGIN.setBackground(new java.awt.Color(0, 102, 102));
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("LOG IN");
        LOGIN.setBorder(null);
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_project/icons8-user-20.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_project/icons8-lock-20 (1).png"))); // NOI18N

        LOGOUT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_project/icons8-home-30.png"))); // NOI18N
        LOGOUT.setBorder(null);
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(SHOW)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(USERID, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(USERID, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SHOW))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        dispose(); // Close the current STUDENT frame

        // Open the FACADE frame
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FACADE().setVisible(true);
            }
        });
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        String userID = USERID.getText();
        String password = new String(PASSWORD.getPassword());

        if (userID.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please complete the data.");
        } else {
            if (userID.equals("ADMIN") && password.equals("USERDATABASE")) {
                dispose(); // Close the current login frame

                // Open the DATABASE frame
                java.awt.EventQueue.invokeLater(() -> {
                    new DATABASE().setVisible(true);
                });

            } else {
                if (counterFromFacade == 0) {
                    // Read from FACULTY_ACCOUNT.java file and store IDs and passwords in arrays
                    // Use the code to read and process data from FACULTY_ACCOUNT.java file
                    // Example:
                    String fileName = "FACULTY_ACCOUNT.txt"; // Change this to the correct file name

                    ArrayList<String> ID0 = new ArrayList<>();
                    ArrayList<String> PASS0 = new ArrayList<>();
                    ArrayList<String> LN0 = new ArrayList<>();
                    ArrayList<String> FN0 = new ArrayList<>();
                    ArrayList<String> SUB0 = new ArrayList<>();

                    try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split("\\s+");
                            ID0.add(parts[2]); // Assuming userID is at index 2 in the file
                            PASS0.add(parts[3]); // Assuming password is at index 3 in the file
                            LN0.add(parts[0]); // Assuming last name is at index 0 in the file
                            FN0.add(parts[1]);
                            SUB0.add(parts[4]);
                        }
                    } catch (IOException e) {
                        e.printStackTrace(); // Handle the exception properly in your application
                    }

                    int index = ID0.indexOf(userID);
                    if (index != -1 && PASS0.get(index).equals(password)) {
                        dispose(); // Close the current login frame

                        String lastName = LN0.get(index);
                        String firstName = FN0.get(index);
                        String course = SUB0.get(index);

                        openFacultyFrame(userID, lastName, firstName, course);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Input.");
                        clearUserInput();
                    }
                } else if (counterFromFacade == 1) {
                    // Read from STUDENT_ACCOUNT.java file and store IDs and passwords in arrays
                    String fileName = "STUDENT_ACCOUNT.txt"; // Change this to the correct file name

                    ArrayList<String> ID1 = new ArrayList<>();
                    ArrayList<String> PASS1 = new ArrayList<>();
                    ArrayList<String> LN1 = new ArrayList<>();
                    ArrayList<String> FN1 = new ArrayList<>();

                    try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split("\\s+");
                            ID1.add(parts[2]); // Assuming userID is at index 2 in the file
                            PASS1.add(parts[3]); // Assuming password is at index 3 in the file
                            LN1.add(parts[0]); // Assuming last name is at index 0 in the file
                            FN1.add(parts[1]);
                        }
                    } catch (IOException e) {
                        e.printStackTrace(); // Handle the exception properly in your application
                    }

                    int index = ID1.indexOf(userID);
                    if (index != -1 && PASS1.get(index).equals(password)) {
                        dispose(); // Close the current login frame

                        String lastName = LN1.get(index);
                        String firstName = FN1.get(index);
                        openStudentFrame(userID, lastName, firstName);
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Input.");
                        clearUserInput();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Counter value not recognized.");
                }
            }
        }
    }//GEN-LAST:event_LOGINActionPerformed

    private void SHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWActionPerformed
        if (SHOW.isSelected()) {
            PASSWORD.setEchoChar((char) 0); // Shows the actual characters
        } else {
            PASSWORD.setEchoChar('*'); // Hides the characters and displays dots (•)
        }
    }//GEN-LAST:event_SHOWActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed

    }//GEN-LAST:event_PASSWORDActionPerformed

    private void USERIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERIDActionPerformed

    }//GEN-LAST:event_USERIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGIN;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JCheckBox SHOW;
    private javax.swing.JTextField USERID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
