/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

import javax.swing.JComboBox;
import java.io.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class SEM1 extends javax.swing.JFrame {

    private String userID;
    private String lastName;
    private String firstName;

    /**
     * Creates new form SEM1
     */
    public SEM1(String userID, String lastName, String firstName) {
        this.userID = userID;
        this.lastName = lastName;
        this.firstName = firstName;
    
        initComponents();
        setupComboBoxActionListener();
        setNameLabel(userID, lastName, firstName);
        
        loadGRADEData("SEM1DAT.txt", SEM1);
    }

    private void setNameLabel(String userID, String lastName, String firstName) {
        NAME.setText(userID + " | " + lastName + ", " + firstName);
    }
    
    private void setupComboBoxActionListener() {
        CHOOSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox<String> combo = (JComboBox<String>) evt.getSource();
                String selectedSemester = (String) combo.getSelectedItem();

                if (selectedSemester.equals("SEMESTER 2")) {
                    dispose(); // Close the current SEM1 frame

                    // Open SEM2 frame and pass the user details
                    java.awt.EventQueue.invokeLater(() -> {
                        new SEM2(userID, lastName, firstName).setVisible(true);
                    });
                }
            }
        });
    }

    private void loadGRADEData(String fileName, javax.swing.JTable table) {
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0); // Clear the table before loading new data
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split("\\s+");
                
                if (data.length >= 8 && data[3].equals(userID)) {
                    Object[] rowData = new Object[]{data[1], data[7]};
                    model.addRow(rowData);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private double computeGWA() {
        DefaultTableModel model = (DefaultTableModel) SEM1.getModel();
        int rowCount = model.getRowCount();
        double sum = 0.0;

        for (int i = 0; i < rowCount; i++) {
            Object value = model.getValueAt(i, 1); // Assuming grades are in the second column
            if (value instanceof String) {
                try {
                    double grade = Double.parseDouble((String) value);
                    sum += grade;
                } catch (NumberFormatException e) {
                    // Handle parsing error if needed
                }
            }
        }

        if (rowCount != 0) {
            return sum / rowCount;
        } else {
            return 0.0; // Return 0 if there are no rows to prevent division by zero
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JButton();
        CHOOSER = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        SEM1 = new javax.swing.JTable();
        COMPUTE = new javax.swing.JButton();
        GWA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentGradingSystem");
        setLocation(new java.awt.Point(500, 180));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        LOGOUT.setBackground(new java.awt.Color(0, 102, 102));
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setText("LOG OUT");
        LOGOUT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        CHOOSER.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CHOOSER.setForeground(new java.awt.Color(0, 102, 102));
        CHOOSER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMESTER 1", "SEMESTER 2" }));
        CHOOSER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        CHOOSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOOSERActionPerformed(evt);
            }
        });

        SEM1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        SEM1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COURSE CODE", "GRADE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SEM1.setAlignmentX(1.0F);
        SEM1.setAlignmentY(1.0F);
        SEM1.setGridColor(new java.awt.Color(0, 102, 102));
        SEM1.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(SEM1);

        COMPUTE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        COMPUTE.setForeground(new java.awt.Color(0, 102, 102));
        COMPUTE.setText("COMPUTE GWA");
        COMPUTE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        COMPUTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPUTEActionPerformed(evt);
            }
        });

        GWA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop_project/icons8-plasmid-40.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STUDENT GRADING SYSTEM");

        NAME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LOGOUT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(CHOOSER, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(GWA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(COMPUTE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addGap(36, 36, 36)
                .addComponent(LOGOUT)
                .addGap(18, 18, 18)
                .addComponent(CHOOSER, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GWA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(COMPUTE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        dispose(); // Close the current STUDENT frame

        // Open the FACADE frame
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FACADE().setVisible(true);
            }
        });
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void COMPUTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPUTEActionPerformed
        double gwa = computeGWA();
        GWA.setText(String.format("%.2f", gwa));                    
    }//GEN-LAST:event_COMPUTEActionPerformed

    private void CHOOSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOOSERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHOOSERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEM1("NOT FOUND", " NOT FOUND", " NOT FOUND").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CHOOSER;
    private javax.swing.JButton COMPUTE;
    private javax.swing.JTextField GWA;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JLabel NAME;
    private javax.swing.JTable SEM1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
