/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author Acer
 */
public class CALCULATOR extends javax.swing.JFrame {

    /**
     * Creates new form CALCULATOR
     */
    
    double num, result;
    int compute;
    
    public CALCULATOR() {
        initComponents();
        
        ON.setEnabled(false);       // Disables the On button
    }
    
    public void COMPUTE()
    {
        switch(compute)
        {
            case 1: result = num + Double.parseDouble(RESULT.getText());
                    RESULT.setText(Double.toString(result));
                    break;
            case 2: result = num - Double.parseDouble(RESULT.getText());
                    RESULT.setText(Double.toString(result));
                    break;
            case 3: result = num / Double.parseDouble(RESULT.getText());
                    RESULT.setText(Double.toString(result));
                    break;
           default: result = num * Double.parseDouble(RESULT.getText());
                    RESULT.setText(Double.toString(result));
        }
    }
    
    public void enable()
    {
        RESULT.setEnabled(true);
        
        ON.setEnabled(false);
        OFF.setEnabled(true);
        
        ZERO.setEnabled(true);
        ONE.setEnabled(true);
        TWO.setEnabled(true);
        THREE.setEnabled(true);
        FOUR.setEnabled(true);
        FIVE.setEnabled(true);
        SIX.setEnabled(true);
        SEVEN.setEnabled(true);
        EIGHT.setEnabled(true);
        NINE.setEnabled(true);
        CLEAR.setEnabled(true);
        DELETE.setEnabled(true);
        EQUALS.setEnabled(true);
        ADD.setEnabled(true);
        SUB.setEnabled(true);
        DIV.setEnabled(true);
        MULT.setEnabled(true);
    }
    
    public void disable()
    {
        RESULT.setEnabled(false);
        
        ON.setEnabled(true);
        OFF.setEnabled(false);
        
        ZERO.setEnabled(false);
        ONE.setEnabled(false);
        TWO.setEnabled(false);
        THREE.setEnabled(false);
        FOUR.setEnabled(false);
        FIVE.setEnabled(false);
        SIX.setEnabled(false);
        SEVEN.setEnabled(false);
        EIGHT.setEnabled(false);
        NINE.setEnabled(false);
        CLEAR.setEnabled(false);
        DELETE.setEnabled(false);
        EQUALS.setEnabled(false);
        MULT.setEnabled(false);
        ADD.setEnabled(false); 
        SUB.setEnabled(false); 
        DIV.setEnabled(false); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        RESULT = new javax.swing.JTextField();
        ON = new javax.swing.JRadioButton();
        OFF = new javax.swing.JRadioButton();
        CLEAR = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        ADD = new javax.swing.JButton();
        SUB = new javax.swing.JButton();
        THREE = new javax.swing.JButton();
        ONE = new javax.swing.JButton();
        ZERO = new javax.swing.JButton();
        TWO = new javax.swing.JButton();
        FOUR = new javax.swing.JButton();
        FIVE = new javax.swing.JButton();
        SIX = new javax.swing.JButton();
        SEVEN = new javax.swing.JButton();
        DIV = new javax.swing.JButton();
        EIGHT = new javax.swing.JButton();
        NINE = new javax.swing.JButton();
        EQUALS = new javax.swing.JButton();
        MULT = new javax.swing.JButton();
        TEMP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        RESULT.setEditable(false);
        RESULT.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        RESULT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        RESULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTActionPerformed(evt);
            }
        });

        buttonGroup1.add(ON);
        ON.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ON.setText("On");
        ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONActionPerformed(evt);
            }
        });

        buttonGroup1.add(OFF);
        OFF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        OFF.setText("Off");
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });

        CLEAR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        DELETE.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DELETE.setText("C");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        ADD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ADD.setText("+");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        SUB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SUB.setText("-");
        SUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBActionPerformed(evt);
            }
        });

        THREE.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        THREE.setText("3");
        THREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THREEActionPerformed(evt);
            }
        });

        ONE.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ONE.setText("1");
        ONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONEActionPerformed(evt);
            }
        });

        ZERO.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ZERO.setText("0");
        ZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZEROActionPerformed(evt);
            }
        });

        TWO.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TWO.setText("2");
        TWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOActionPerformed(evt);
            }
        });

        FOUR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        FOUR.setText("4");
        FOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOURActionPerformed(evt);
            }
        });

        FIVE.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        FIVE.setText("5");
        FIVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIVEActionPerformed(evt);
            }
        });

        SIX.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SIX.setText("6");
        SIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIXActionPerformed(evt);
            }
        });

        SEVEN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SEVEN.setText("7");
        SEVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEVENActionPerformed(evt);
            }
        });

        DIV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DIV.setText("/");
        DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVActionPerformed(evt);
            }
        });

        EIGHT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        EIGHT.setText("8");
        EIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIGHTActionPerformed(evt);
            }
        });

        NINE.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NINE.setText("9");
        NINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NINEActionPerformed(evt);
            }
        });

        EQUALS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        EQUALS.setText("=");
        EQUALS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EQUALSActionPerformed(evt);
            }
        });

        MULT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MULT.setText("*");
        MULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTActionPerformed(evt);
            }
        });

        TEMP.setForeground(new java.awt.Color(0, 153, 0));
        TEMP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("LATORRE, JEO D. || BSCS 2C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(TEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(RESULT, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CLEAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ZERO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ONE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TWO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(THREE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SUB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIVE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SIX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SEVEN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DIV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EIGHT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NINE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EQUALS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MULT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RESULT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ON)
                    .addComponent(OFF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLEAR)
                    .addComponent(DELETE)
                    .addComponent(ADD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(THREE)
                    .addComponent(SUB)
                    .addComponent(ZERO)
                    .addComponent(ONE)
                    .addComponent(TWO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEVEN)
                    .addComponent(DIV)
                    .addComponent(FOUR)
                    .addComponent(FIVE)
                    .addComponent(SIX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MULT)
                    .addComponent(EIGHT)
                    .addComponent(NINE)
                    .addComponent(EQUALS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        int length = RESULT.getText().length();
        int number = RESULT.getText().length() - 1;
        String Container;
        
        if(length > 0)
        {
            StringBuilder back = new StringBuilder(RESULT.getText());
            back.deleteCharAt(number);
            Container = back.toString();
            RESULT.setText(Container);
        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        num = Double.parseDouble(RESULT.getText());
        compute = 1;
        RESULT.setText("");
        TEMP.setText(num + "+");
    }//GEN-LAST:event_ADDActionPerformed

    private void SUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBActionPerformed
        num = Double.parseDouble(RESULT.getText());
        compute = 2;
        RESULT.setText("");
        TEMP.setText(num + "-");
    }//GEN-LAST:event_SUBActionPerformed

    private void THREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THREEActionPerformed
        RESULT.setText(RESULT.getText() + "3");
    }//GEN-LAST:event_THREEActionPerformed

    private void ONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONEActionPerformed
        RESULT.setText(RESULT.getText() + "1");
    }//GEN-LAST:event_ONEActionPerformed

    private void ZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZEROActionPerformed
        RESULT.setText(RESULT.getText() + "0");
    }//GEN-LAST:event_ZEROActionPerformed

    private void TWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOActionPerformed
        RESULT.setText(RESULT.getText() + "2");
    }//GEN-LAST:event_TWOActionPerformed

    private void FOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOURActionPerformed
        RESULT.setText(RESULT.getText() + "4");
    }//GEN-LAST:event_FOURActionPerformed

    private void FIVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIVEActionPerformed
        RESULT.setText(RESULT.getText() + "5");
    }//GEN-LAST:event_FIVEActionPerformed

    private void SIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIXActionPerformed
        RESULT.setText(RESULT.getText() + "6");
    }//GEN-LAST:event_SIXActionPerformed

    private void SEVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEVENActionPerformed
        RESULT.setText(RESULT.getText() + "7");
    }//GEN-LAST:event_SEVENActionPerformed

    private void DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVActionPerformed
        num = Double.parseDouble(RESULT.getText());
        compute = 3;
        RESULT.setText("");
        TEMP.setText(num + "/");
    }//GEN-LAST:event_DIVActionPerformed

    private void EIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIGHTActionPerformed
        RESULT.setText(RESULT.getText() + "8");
    }//GEN-LAST:event_EIGHTActionPerformed

    private void NINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NINEActionPerformed
        RESULT.setText(RESULT.getText() + "9");
    }//GEN-LAST:event_NINEActionPerformed

    private void EQUALSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EQUALSActionPerformed
        COMPUTE();
        TEMP.setText("");
    }//GEN-LAST:event_EQUALSActionPerformed

    private void MULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTActionPerformed
        num = Double.parseDouble(RESULT.getText());
        compute = 4;
        RESULT.setText("");
        TEMP.setText(num + "*");
    }//GEN-LAST:event_MULTActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        RESULT.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void RESULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESULTActionPerformed

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFActionPerformed
        disable();
    }//GEN-LAST:event_OFFActionPerformed

    private void ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONActionPerformed
        enable();
    }//GEN-LAST:event_ONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULATOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton DIV;
    private javax.swing.JButton EIGHT;
    private javax.swing.JButton EQUALS;
    private javax.swing.JButton FIVE;
    private javax.swing.JButton FOUR;
    private javax.swing.JButton MULT;
    private javax.swing.JButton NINE;
    private javax.swing.JRadioButton OFF;
    private javax.swing.JRadioButton ON;
    private javax.swing.JButton ONE;
    private javax.swing.JTextField RESULT;
    private javax.swing.JButton SEVEN;
    private javax.swing.JButton SIX;
    private javax.swing.JButton SUB;
    private javax.swing.JLabel TEMP;
    private javax.swing.JButton THREE;
    private javax.swing.JButton TWO;
    private javax.swing.JButton ZERO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
